### ISSUE TITLE
HTML interpretation of rants and comments

### ISSUE THREAD

**Issue by BixelPitch** [tahnik/devRantron#184]
Hey devs of devrantron. As mentionend in 

https://www.devrant.io/rants/818876

every rant or comment is interpreted by the devrantron client. The official website and app don't do that and in my opinion, devrant should be displayed equal on platforms. It's a design question and it's up to you how you handle it ;) Thanks for your nice work, keep it up!

**Comment by hex2f** [comment]
Yeah, this is quite serious. It does not allow for <script> since react is smart enough to ignore that. Will have a look at it.

Although, part of me wants to make this a setting with a more controlled filtering of tags to add effect to rants. It's really funny seeing massive text to emphasise the point :thinking:

**Comment by DFoxinator** [comment]
I think text formatting is fun for a week and then everyone gets tired of it and it becomes more of a way to spam/be annoying than actually increase the quality of rants. We purposely don't format anything (even links) on the main rant feed because we stress the importance of the quality of the rant over how it's formatted/how much space it takes up. That's another reason why rants containing images get slightly down-weighted - because they stand out more in the feed and hence get more attention, naturally. 

Also, just to add here - even if we did decide to allow some kind of reasonable formatting, it would not be done through HTML but rather markdown as has been requested pretty thoroughly. Official ticket is here, with some limited discussion but more thoughts are of course appreciated: https://github.com/devRant/devRant/issues/27
